### ISSUE TITLE
Purchase Receipt and Stock Reconciliation

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#21]
While submitting its throwing following error.

![warehouse](https://user-images.githubusercontent.com/24898695/39816102-d7a30b48-53b7-11e8-8c00-a5e948e85235.png)

**Comment by umairsy** [comment]
Please check if this Account is mentioned for this warehouse, or it's parent.

**Comment by umairsy** [comment]
If you have created separate Account for the Warehouse as well, then just ensure that that Account is updated in the Warehouse master as well, so that they are linked.

After doing this linking, reselect Warehouse in the Purchase Receipt and then try to submit it.

@gaurav-naik please provide any further support, if needed.

**Comment by gaurav-naik** [comment]
I am assuming this was on the live server. The error should not recur now. Kindly retry submitting a Purchase Receipt

**Comment by Basawa-SELCO** [comment]
yes, it works now. Can you let us know the change?

**Comment by umairsy** [comment]
Hi,

There was a change in the functionality itself. In version 7, each Warehouse was linked to a specific accounting ledger. But in version 10, if you don't have an account for Warehouse, it takes account of the respective parent. Where was some linking missing for some warehouse, which I believe has been fixed by Gaurav.

Can we close this issue?
