### ISSUE TITLE
GST Invoice Print Format

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#24]
In Standard GST Invoice Print Format not able to add Standard Field like DC Number.

**Comment by gaurav-naik** [comment]
The DC Number field will appear in the print format if it is present on the Sales Invoice. There is no such field on Sales Invoice in v7 (and therefore in v10) currently.

**Comment by Basawa-SELCO** [comment]
We are trying to add the Delivery Note field to the Standard ERP GST Report by using the Drag and Drop feature. But the Delivery Note Field is not displayed in the Left pane from where we can drag and drop though Delivery Note is present inside the Child table in the Invoice.

Please refer the SELCO GST Sales Invoice format.

**Comment by gaurav-naik** [comment]
Since the Delivery Note field is on the Sales Invoice Item doctype, it will not be visible in the left hand pane. Instead you will find it on clicking the Select Columns button in Items.

![delivery_note_field](https://user-images.githubusercontent.com/17795124/40599441-f3a00974-626a-11e8-817b-c53bd9302b03.gif)

**Comment by Basawa-SELCO** [comment]
Works fine
